### ISSUE TITLE
Page keeps refreshing in Safari

### ISSUE THREAD

**Issue by mrkickling** [watson-developer-cloud/visual-recognition-nodejs#237]
When using your website in Safari the page just keeps refreshing continuously. Very frustrating. I am using Safari 9.0.1.

**Comment by kognate** [comment]
I'm sorry to hear you hare having problems.   

Could you paste in what the page http://www.whatsmyua.com/  tells you about your user agent please?

**Comment by mrkickling** [comment]
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4",
  "browser": {
    "name": "Safari",
    "version": "9.0.3",
    "major": "9"
  },
  "engine": {
    "version": "601.4.4",
    "name": "WebKit"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.11.3"
  },
  "device": {},
  "cpu": {}
}

(So I guess it was Safari 9.0.3 not 9.0.1)

**Comment by nfriedly** [comment]
Do either of these urls work for you?

* Should load a pre-trained classifier: https://visual-recognition-demo.mybluemix.net/train?classifier_id=DogBreeds_1865955235&name=Dog%20Breeds&kind=dogs&expires=Mon%20Oct%2031%202016%2011%3A31%3A00%20GMT-0400%20(EDT)
* Should display an expired error: https://visual-recognition-demo.mybluemix.net/train?classifier_id=DogBreeds_1865955235&name=Dog%20Breeds&kind=dogs&expires=Mon%20Oct%2030%202016%2011%3A31%3A00%20GMT-0400%20(EDT)

**Comment by nfriedly** [comment]
Actually, nevermind, I'm pretty sure it's the Bug in Safari mentioned here: http://stackoverflow.com/questions/28441025/ignore-safaris-initial-page-load-popstate#29605198

It appears to be fixed in newer versions of Safari, so it should work for you if you can update to a current release. 

I will also see if I can implement the workaround mentioned on Stack Overflow, but it will probably be a few weeks because I'm leaving the country at the end of the week.

**Comment by mrkickling** [comment]
Thanks! Please update me if it gets fixed:)

**Comment by germanattanasio** [comment]
I'm going to close this because it looks like it only affects older versions of Safari browsers. Based on Nathan's comment, safari versions from 2016 already fixed this.
