### ISSUE TITLE
Chunk images for some browsers

### ISSUE THREAD

**Issue by jzhang300** [watson-developer-cloud/visual-recognition-nodejs#77]
Some browsers cannot handle loading hundreds of images at once and will consequently crash.  However, it will not crash if images were loaded one chunk at a time.

The limit is around 55-57mb of data at a time.

EDIT:

Do browser detection, and generate message about browsers accordingly.

**Comment by kathrynmcelroy** [comment]
We will reopen this issue to discuss alternative wording.

Current wording:
<img width="777" alt="screen shot 2016-04-15 at 2 02 22 pm" src="https://cloud.githubusercontent.com/assets/5400092/14573095/74ad9702-0318-11e6-8c3b-5023e4fda605.png">

**Comment by kathrynmcelroy** [comment]
Tip: Because of the browser you're using, try not to upload more than 55mb at a time. 

Tip: The browser you're using may not be able to handle more than 55mb of images uploaded at a time. 

Tip: Try uploading less than 55mb at a time for the best browser experience.

Or: suggestion, heads up, etc. instead of "tip"

**Comment by jzhang300** [comment]
Ok, just let me know what's the final wording and I'll put it in.

**Comment by kathrynmcelroy** [comment]
Final wording:
Tip: We recommend uploading less than 55mb of images at a time for the best experience in your current browser.

**Comment by melissamahoney3** [comment]
@jzhang300 @kathrynmcelroy Sorry for getting to this late, I was out on Friday. Its typically against IBM Style to use "we". I also don't think it should just be a "Tip", since it can crash your browser, it should probably be "Important".

So how about:

Important: Upload less than 55MB of images at a time for the best experience in your current browser.

**Comment by kathrynmcelroy** [comment]
@melissamahoney3 That's good to know!

I like this one. My only other thought is to soften it a bit by making "upload" into a gerund:
"Important: Uploading less than 55mb of images at a time will deliver the best experience in your current browser."

I'd be fine with either. What does everyone else think?

**Comment by kathrynmcelroy** [comment]
After discussing, Melissa made the great point that the non-gerund is more straight forward and matches command-line tenses. Since our dev user is more used to that, we'll stick with her original suggestion:

Important: Upload less than 55MB of images at a time for the best experience in your current browser.

Please add thumbs up to agree, or make another suggestion.
